name: .NET Core

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: mywebapdemo
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'

    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
